/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ys386.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;
  final AbstractShipFactory<Character> shipFactory;

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
    this.shipFactory = new V1ShipFactory();
  }

  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  public void doOnePlacement() throws IOException {
    String prompt = "Where would you like to put your ship?";
    Placement p = readPlacement(prompt);
    Ship<Character> s = shipFactory.makeDestroyer(p);
    theBoard.tryAddShip(s);
    prompt = view.displayMyOwnBoard();
    out.println(prompt);
  }

  public static void main(String[] args) throws IOException {
    Board<Character> theBoard = new BattleShipBoard<>(10, 20);
    InputStreamReader isr = new InputStreamReader(System.in);
    App app = new App(theBoard, isr, System.out);
    app.doOnePlacement();
  }
}
